# Generated by Django 4.2.4 on 2023-08-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Article name')),
                ('slug_name', models.CharField(default='', max_length=500, unique=True, verbose_name='Slug name')),
                ('body', models.TextField(verbose_name='Article body')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Slug name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Topic name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('slug_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Slug name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
