# Generated by Django 4.2.3 on 2023-07-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_name',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Slug name'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Slug name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Article name'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Topic name'),
        ),
    ]
