# Generated by Django 4.2.3 on 2023-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_article_creator_reader_tag_topic_delete_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='department',
            field=models.CharField(default='Newspaper', max_length=200, verbose_name='Department name'),
        ),
    ]
