# Generated by Django 4.2.3 on 2023-07-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_article_slug_name_topic_description_topic_slug_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
