# Generated by Django 4.2.3 on 2023-07-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_tag_slug_name_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Slug name'),
        ),
    ]
