from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls')),
    
    # path('docs/', include()) - docs view for Sphinx/Autogenerated schema
    
    path("api/", include("djoser.urls")),
    path("api/", include("users.urls")),
    path('auth/', include('djoser.social.urls')),
    
]
