from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls')),

    # path('docs/', include()) - docs view for Sphinx/Autogenerated schema
    
    path("api/", include("djoser.urls")),
    path("api/", include("users.urls")),
    path('auth/', include('djoser.social.urls')),
    
]
